# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: catalog-api
# spec:
#   selector:
#     matchLabels:
#       app: catalog-api
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: catalog-api
#     spec:
#       containers:
#       - name: catalog-api
#         image: armcontainerregistry01.azurecr.io/catalog-api:latest
#         ports:
#         - containerPort: 3000

# ---

apiVersion: v1
kind: Service
metadata:
  name: catalog-api-service
spec:
  selector:
    app: catalog-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
